RenetVisualizer: Update egui to 0.23
since visualizer uses 0.22, trying to use both versions leads to an error about mismatched types when trying to use it:
```
error[E0308]: mismatched types
...
    = note: `bevy_egui::egui::Context` and `egui::context::Context` have similar names, but are actually distinct types
...
    = note: perhaps two different versions of crate `egui` are being used?
```